version: '3.9'
services:
  backend: 
    container_name: wb-api
    restart: always
    build:
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    volumes:
      - postgres_data:/data/postgres
    image: postgres
    restart: always
    env_file:
       - .env
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  postgres_data:
